from __future__ import annotations

from typing import Dict, Optional

from .dataset_schema import ModelConfig, TrainConfig


TRAIN_ROOT = "./final_experiments_for_paper/experiment2_style_model/trained_models"
SUMMARY_ROOT = "./final_experiments_for_paper/experiment2_style_model/training_summary"


def make_config(
    *,
    study_name: str,
    train_dir: str,
    eval_dir: str,
    pair_variant: str,
    seed: int,
    embedding_dim: int,
    batch_size: int,
    lr: float,
    tau: float,
    phi_variant: str,
    epochs: int = 6,
    max_steps_per_epoch: Optional[int] = None,
    max_eval_batches: int = 250,
    num_workers: int = 0,
    max_train_rows: Optional[int] = None,
    max_eval_rows: Optional[int] = None,
    persistent_workers: bool = False,
    init_from_checkpoint: Optional[str] = None,
    init_reset_optimizer: bool = True,
    init_strict_load: bool = True,
) -> TrainConfig:
    model = ModelConfig(
        name=f"{phi_variant}_edim{embedding_dim}",
        embedding_dim=embedding_dim,
        token_embed_dim=96,
        hidden_dim=256 if embedding_dim <= 256 else 384,
        num_board_layers=2,
        dropout=0.1,
        variant_name=phi_variant,
        use_game_type=(phi_variant in {"phi1", "phi3"}),
        use_phase=False,
        use_opening=False,
    )

    return TrainConfig(
        study_name=study_name,
        train_dir=train_dir,
        eval_dir=eval_dir,
        trained_models_root=TRAIN_ROOT,
        training_summary_root=SUMMARY_ROOT,
        pair_variant=pair_variant,
        seed=seed,
        epochs=epochs,
        batch_size=batch_size,
        lr=lr,
        tau=tau,
        num_workers=num_workers,
        prefetch_factor=4,
        persistent_workers=persistent_workers,
        model=model,
        max_eval_batches=max_eval_batches,
        keep_last_n_checkpoints=2,
        timeout_minutes=8 * 60,
        max_steps_per_epoch=max_steps_per_epoch,
        max_train_rows=max_train_rows if max_train_rows is not None else 1_000_000_000,
        max_eval_rows=max_eval_rows if max_eval_rows is not None else 1_000_000_000,
        init_from_checkpoint=init_from_checkpoint,
        init_reset_optimizer=init_reset_optimizer,
        init_strict_load=init_strict_load,
    )

STUDIES: Dict[str, TrainConfig] = {
    "screen_v1_phi0_tau0_05": make_config(
        study_name="screen_v1_phi0_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi0_tau0_10": make_config(
        study_name="screen_v1_phi0_tau0_10",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi0_tau0_25": make_config(
        study_name="screen_v1_phi0_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi0_tau0_75": make_config(
        study_name="screen_v1_phi0_tau0_75",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi0_tau1_25": make_config(
        study_name="screen_v1_phi0_tau1_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=1.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi1_tau0_75": make_config(
        study_name="screen_v1_phi1_tau0_75",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "debug_small": make_config(
        study_name="debug_small",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=128,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi0",
        epochs=2,
        max_steps_per_epoch=50,
        max_eval_batches=20,
        num_workers=0,
    ),



    "final_v1_phi0_besttau": make_config(
        study_name="final_v1_phi0_besttau",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,  # replace with winner
        phi_variant="phi0",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
    "final_v1_phi1_besttau": make_config(
        study_name="final_v1_phi1_besttau",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,  # replace if needed
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),


    "screen_v2_phi0_besttau_from_v1": make_config(
        study_name="screen_v2_phi0_besttau_from_v1",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,  # plug in best phi0 tau from v1 screen
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v2_phi1_besttau_from_v1": make_config(
        study_name="screen_v2_phi1_besttau_from_v1",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,  # plug in best phi1 tau from v1 if different
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    # if v2 screen looks better run this
    "final_v2_best": make_config(
        study_name="final_v2_best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,  # winner
        phi_variant="phi0",  # or phi1 winner
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),

    # once v3 is ready
    "screen_v3_phi0_besttau_from_v1": make_config(
        study_name="screen_v3_phi0_besttau_from_v1",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi1_besttau_from_v1": make_config(
        study_name="screen_v3_phi1_besttau_from_v1",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),


    # Once phi3 is ready
    "screen_v1_phi3_besttau": make_config(
        study_name="screen_v1_phi3_besttau",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi3",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v2_phi3_besttau": make_config(
        study_name="screen_v2_phi3_besttau",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi3",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi3_besttau": make_config(
        study_name="screen_v3_phi3_besttau",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi3",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
}

STUDIES.update({
    "screen_v1_phi1_tau0_05": make_config(
        study_name="screen_v1_phi1_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi1_tau0_10": make_config(
        study_name="screen_v1_phi1_tau0_10",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi1_tau0_25": make_config(
        study_name="screen_v1_phi1_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v1_phi1_tau1_25": make_config(
        study_name="screen_v1_phi1_tau1_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=1.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    "screen_v2_phi0_tau0_05": make_config(
        study_name="screen_v2_phi0_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v2_phi0_tau0_75": make_config(
        study_name="screen_v2_phi0_tau0_75",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v2_phi0_tau1_25": make_config(
        study_name="screen_v2_phi0_tau1_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=1.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    "screen_v2_phi1_tau0_05": make_config(
        study_name="screen_v2_phi1_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v2_phi1_tau0_75": make_config(
        study_name="screen_v2_phi1_tau0_75",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v2_phi1_tau1_25": make_config(
        study_name="screen_v2_phi1_tau1_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=1.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
})


STUDIES.update({
    "screen_v3_phi0_tau0_05": make_config(
        study_name="screen_v3_phi0_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi0_tau0_25": make_config(
        study_name="screen_v3_phi0_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi0_tau0_75": make_config(
        study_name="screen_v3_phi0_tau0_75",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi0_tau1_25": make_config(
        study_name="screen_v3_phi0_tau1_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=1.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    "screen_v3_phi1_tau0_05": make_config(
        study_name="screen_v3_phi1_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi1_tau0_25": make_config(
        study_name="screen_v3_phi1_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi1_tau0_75": make_config(
        study_name="screen_v3_phi1_tau0_75",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.75,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "screen_v3_phi1_tau1_25": make_config(
        study_name="screen_v3_phi1_tau1_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=1.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
})

STUDIES.update({
    # Repair v2 screens that were previously run against the wrong cache.
    "repair_v2_phi0_tau0_10": make_config(
        study_name="repair_v2_phi0_tau0_10",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "repair_v2_phi0_tau0_25": make_config(
        study_name="repair_v2_phi0_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "repair_v2_phi1_tau0_10": make_config(
        study_name="repair_v2_phi1_tau0_10",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    # Finalists to support paper plots/metrics once repaired v2 comparison is available.
    "final_v1_phi0_tau0_05": make_config(
        study_name="final_v1_phi0_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi0",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
    "final_v1_phi1_tau0_25": make_config(
        study_name="final_v1_phi1_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),

    # Placeholder finalist for v2 winner after repair.
    # Keep only one of phi0/phi1 once you see which repaired screen is best.
    "final_v2_phi0_tau0_25_if_winner": make_config(
        study_name="final_v2_phi0_tau0_25_if_winner",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
    "final_v2_phi1_tau0_10_if_winner": make_config(
        study_name="final_v2_phi1_tau0_10_if_winner",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
})


STUDIES.update({
    "ablation_v1_phi0_tau0_05_bs2048": make_config(
        study_name="ablation_v1_phi0_tau0_05_bs2048",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=2048,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    "ablation_v1_phi0_tau0_05_lr0_001": make_config(
        study_name="ablation_v1_phi0_tau0_05_lr0_001",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=1e-3,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    "final_v1_phi1_tau0_05": make_config(
        study_name="final_v1_phi1_tau0_05",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),

    "repair_v2_phi1_tau0_25": make_config(
        study_name="repair_v2_phi1_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),

    "final_v1_phi1_tau0_10": make_config(
        study_name="final_v1_phi1_tau0_10",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
})


V2_PHI0_BEST_SCREEN_CKPT = (
    "./final_experiments_for_paper/experiment2_style_model/trained_models/"
    "screen_v2_phi0_tau0_10__pair-v2__phi-phi0__edim-256__bs-4096__lr-0.0003__tau-0.1__seed-42/"
    "best.pt"
)

V2_PHI1_BEST_SCREEN_CKPT = (
    "./final_experiments_for_paper/experiment2_style_model/trained_models/"
    "screen_v2_phi1_tau0_10__pair-v2__phi-phi1__edim-256__bs-4096__lr-0.0003__tau-0.1__seed-42/"
    "best.pt"
)


STUDIES.update({
    "screen_v3_phi0_warm_tau0_05_from_v2best": make_config(
        study_name="screen_v3_phi0_warm_tau0_05_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI0_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi0_warm_tau0_10_from_v2best": make_config(
        study_name="screen_v3_phi0_warm_tau0_10_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI0_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi0_warm_tau0_25_from_v2best": make_config(
        study_name="screen_v3_phi0_warm_tau0_25_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI0_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi1_warm_tau0_05_from_v2best": make_config(
        study_name="screen_v3_phi1_warm_tau0_05_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI1_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi1_warm_tau0_10_from_v2best": make_config(
        study_name="screen_v3_phi1_warm_tau0_10_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI1_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi1_warm_tau0_25_from_v2best": make_config(
        study_name="screen_v3_phi1_warm_tau0_25_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI1_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "stress_test_v3_phi1_tau0_10_warm_from_v2final": make_config(
        study_name="stress_test_v3_phi1_tau0_10_warm_from_v2final",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
        init_from_checkpoint=(
            "./final_experiments_for_paper/experiment2_style_model/trained_models/"
            "final_v2_phi1_tau0_10_if_winner__pair-v2__phi-phi1__edim-256__bs-4096__lr-0.0003__tau-0.1__seed-42/"
            "best.pt"
        ),
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
})



STUDIES.update({
    "final_v2_phi1_tau0_25_if_winner": make_config(
        study_name="final_v2_phi1_tau0_25_if_winner",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
    "screen_v3_phi0_warm_tau0_05_from_v2best": make_config(
        study_name="screen_v3_phi0_warm_tau0_05_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI0_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi0_warm_tau0_10_from_v2best": make_config(
        study_name="screen_v3_phi0_warm_tau0_10_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI0_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi0_warm_tau0_25_from_v2best": make_config(
        study_name="screen_v3_phi0_warm_tau0_25_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI0_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi1_warm_tau0_05_from_v2best": make_config(
        study_name="screen_v3_phi1_warm_tau0_05_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.05,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI1_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi1_warm_tau0_10_from_v2best": make_config(
        study_name="screen_v3_phi1_warm_tau0_10_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI1_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "screen_v3_phi1_warm_tau0_25_from_v2best": make_config(
        study_name="screen_v3_phi1_warm_tau0_25_from_v2best",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
        init_from_checkpoint=V2_PHI1_BEST_SCREEN_CKPT,
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "final_v3_phi1_tau0_10_warm_from_v2final": make_config(
        study_name="final_v3_phi1_tau0_10_warm_from_v2final",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
        init_from_checkpoint=(
            "./final_experiments_for_paper/experiment2_style_model/trained_models/"
            "final_v2_phi1_tau0_10_if_winner__pair-v2__phi-phi1__edim-256__bs-4096__lr-0.0003__tau-0.1__seed-42/"
            "best.pt"
        ),
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
    "final_v3_phi1_tau0_25_warm_from_v2final": make_config(
        study_name="final_v3_phi1_tau0_25_warm_from_v2final",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
        init_from_checkpoint=(
            "./final_experiments_for_paper/experiment2_style_model/trained_models/"
            "final_v2_phi1_tau0_25_if_winner__pair-v2__phi-phi1__edim-256__bs-4096__lr-0.0003__tau-0.25__seed-42/"
            "best.pt"
        ),
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
})




STUDIES.update({
    "final_v1_phi0_tau0_10": make_config(
        study_name="final_v1_phi0_tau0_10",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.10,
        phi_variant="phi0",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
    "final_v1_phi0_tau0_25": make_config(
        study_name="final_v1_phi0_tau0_25",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi0",
        epochs=8,
        max_steps_per_epoch=750,
        max_eval_batches=150,
        num_workers=0,
    ),
    "ablation_v1_phi0_tau0_05_lr0_01": make_config(
        study_name="ablation_v1_phi0_tau0_05_lr0_01",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v1_cached/eval",
        pair_variant="v1",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=0.01,
        tau=0.05,
        phi_variant="phi0",
        epochs=3,
        max_steps_per_epoch=200,
        max_eval_batches=40,
        num_workers=0,
    ),
    "super_v2_phi1_tau0_25_if_winner": make_config(
        study_name="super_v2_phi1_tau0_25_if_winner",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v2",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=5000,
        max_eval_batches=150,
        num_workers=0,
    ),
    "super_v3_phi1_tau0_25_warm_from_v2final": make_config(
        study_name="super_v3_phi1_tau0_25_warm_from_v2final",
        train_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v3_cached/train",
        eval_dir="./final_experiments_for_paper/experiment2_style_model/pairs_v2_cached/eval",
        pair_variant="v3",
        seed=42,
        embedding_dim=256,
        batch_size=4096,
        lr=3e-4,
        tau=0.25,
        phi_variant="phi1",
        epochs=8,
        max_steps_per_epoch=5000,
        max_eval_batches=150,
        num_workers=0,
        init_from_checkpoint=(
            "./final_experiments_for_paper/experiment2_style_model/trained_models/"
            "super_v2_phi1_tau0_25_if_winner__pair-v2__phi-phi1__edim-256__bs-4096__lr-0.0003__tau-0.25__seed-42/"
            "best.pt"
        ),
        init_reset_optimizer=True,
        init_strict_load=True,
    ),
})


